function [] = plotTrip(traj, Grid)
%plotTrip.m - Plot trip
%
%DESCRIPTION:
%Plots the trajectory on the Tisserand graph
%
%INPUTS
%-traj:
%   Trajectory to plot in 2D format. E.g.: [3 3; 2 5; 4 8].
%-Grid:
%   Grid generated by generate_Grid.m.
%
%AUTHOR
%Hadrien AFSA
%
%--------------------------------------------------------------------------
    
    au=getAstroConstants('AU');
    
    for i=1:size(traj,1)
        %Draws the starting and arriving contour
        if i==1 | i==size(traj,1)
            [ra, rp]=modified_generateContours(traj(i,1), traj(i,2), 0, pi);
            plot(ra/au, rp/au, 'k', 'LineWidth', 1);      
            
        %Draws the intermediate contours
        else
            %Finds the first intersection
            if traj(i-1,1)<traj(i,1)    %From inner to outer planet
                int_prec =  Grid(:,1)== traj(i-1,1)& ...
                            Grid(:,4)==traj(i,1) & ...
                            Grid(:,3)==traj(i-1,2) & ...
                            Grid(:,6)==traj(i,2);
                idx_prec = 5;
            else                                %From outer to inner planet
                int_prec =  Grid(:,1)== traj(i,1)& ...
                            Grid(:,4)==traj(i-1,1) & ...
                            Grid(:,3)==traj(i,2) & ...
                            Grid(:,6)==traj(i-1,2);
                idx_prec = 2;
            end
            Grid_prec=Grid(int_prec,:);
            
            %Finds the second intersection
            if traj(i,1)<traj(i+1,1)    %From inner to outer planet
                int_after =  Grid(:,1)== traj(i,1)& ...
                            Grid(:,4)==traj(i+1,1) & ...
                            Grid(:,3)==traj(i,2) & ...
                            Grid(:,6)==traj(i+1,2);
                idx_after = 2;
            else                                %From outer to inner planet
                int_after =  Grid(:,1)== traj(i+1,1)& ...
                            Grid(:,4)==traj(i,1) & ...
                            Grid(:,3)==traj(i+1,2) & ...
                            Grid(:,6)==traj(i,2);
                idx_after = 5;
            end
            Grid_after=Grid(int_after,:);

            %Draws the contour between the two intersections
            [ra, rp]=modified_generateContours(traj(i,1), traj(i,2), Grid_prec(idx_prec), Grid_after(idx_after));
            plot(ra/au, rp/au, 'r', 'LineWidth', 2);
        end
    end
end

